name: Scrape web and post to Discord if necessary
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0/12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Mystery Gifts
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ./mysterygifts.py
      - name: Wowhead Prime Loot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WOW_WEBHOOK_URL }}
        run: |
          ./wowhead.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automatic update"
